### ISSUE TITLE
Error while reuploading the file with the same name for the resource 

### ISSUE THREAD

**Issue by ismail-shahzad** [datopian/ckanext-cloudstorage#3]
Cloudstorage isnt uploading a file with the same name twice for a resource on azure storage as it says that the blob already exists.

## Acceptance
* [x] Reuploading the resource through UI while editing a resource works without errors 

## Tasks
* [x] Debug the cause and apply the necessary fix 

## Steps to replicate the error
* Create a resource through UI with a file uploaded (say abc.csv)
* Once created, edit the resource and reupload the same file and you should be able to see the error pasted below in the `Analysis` section

## Analysis
The following error can be seen in the traceback
```
2022-02-09 11:21:52,271 ERROR [ckan.config.middleware.flask_app] The specified blob already exists.
ckan-dev_1    | RequestId:73df0e7b-801e-006c-6ea7-1d09f0000000
ckan-dev_1    | Time:2022-02-09T11:21:52.2859241Z
ckan-dev_1    | ErrorCode:BlobAlreadyExists
ckan-dev_1    | Error:None
ckan-dev_1    | Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
ckan-dev_1    | RequestId:73df0e7b-801e-006c-6ea7-1d09f0000000
ckan-dev_1    | Time:2022-02-09T11:21:52.2859241Z</Message></Error>
ckan-dev_1    | Traceback (most recent call last):
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
ckan-dev_1    |     return client.upload(
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 212, in upload
ckan-dev_1    |     raise models.StorageErrorException(response, self._deserialize)
ckan-dev_1    | azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'The specified blob already exists.'
ckan-dev_1    | Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
ckan-dev_1    | RequestId:73df0e7b-801e-006c-6ea7-1d09f0000000
ckan-dev_1    | Time:2022-02-09T11:21:52.2859241Z</Message></Error>
ckan-dev_1    | 
ckan-dev_1    | During handling of the above exception, another exception occurred:
ckan-dev_1    | 
ckan-dev_1    | Traceback (most recent call last):
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
ckan-dev_1    |     rv = self.dispatch_request()
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
ckan-dev_1    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/flask/views.py", line 84, in view
ckan-dev_1    |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/flask/views.py", line 158, in dispatch_request
ckan-dev_1    |     return current_app.ensure_sync(meth)(*args, **kwargs)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/config/middleware/../../views/resource.py", line 371, in post
ckan-dev_1    |     get_action(u'resource_update')(context, data)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
ckan-dev_1    |     result = _action(context, data_dict, **kw)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/logic/action/update.py", line 107, in resource_update
ckan-dev_1    |     updated_pkg_dict = _get_action('package_update')(context, pkg_dict)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
ckan-dev_1    |     result = _action(context, data_dict, **kw)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/logic/action/update.py", line 332, in package_update
ckan-dev_1    |     upload.upload(resource['id'], uploader.get_max_resource_size())
ckan-dev_1    |   File "/srv/app/src/ckanext-cloudstorage/ckanext/cloudstorage/storage.py", line 322, in upload
ckan-dev_1    |     blob_client.upload_blob(stream)
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
ckan-dev_1    |     return func(*args, **kwargs)
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/azure/storage/blob/_blob_client.py", line 496, in upload_blob
ckan-dev_1    |     return upload_block_blob(**options)
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/azure/storage/blob/_upload_helpers.py", line 153, in upload_block_blob
ckan-dev_1    |     process_storage_error(error)
ckan-dev_1    |   File "/usr/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
ckan-dev_1    |     raise error
ckan-dev_1    | azure.core.exceptions.ResourceExistsError: The specified blob already exists.
ckan-dev_1    | RequestId:73df0e7b-801e-006c-6ea7-1d09f0000000
ckan-dev_1    | Time:2022-02-09T11:21:52.2859241Z
ckan-dev_1    | ErrorCode:BlobAlreadyExists
ckan-dev_1    | Error:None
ckan-dev_1    | Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
ckan-dev_1    | RequestId:73df0e7b-801e-006c-6ea7-1d09f0000000
ckan-dev_1    | Time:2022-02-09T11:21:52.2859241Z</Message></Error>
ckan-dev_1    | 2022-02-09 11:21:52,341 INFO  [ckan.config.middleware.flask_app]  500 /dataset/test-dataset-local-dev/resource/45f849c0-c817-49c0-8300-055cc48adf7a/edit render time 0.543 seconds
```

It works fine when we edit the resource with a different file upload but fails with the above error for the same file name.

**Comment by sagargg** [comment]
I think both issues are # 1 related to the same cause.

**Comment by ismail-shahzad** [comment]
Yes, both could be related.
